################################################################################
#                                                                              #
#                      L O G I C L A N C E   S Y S T E M                       #
#                                                                              #
#  Module: FPGA Automation Tool — Tcl Config Generator                         #
#  Author: Hemanth Kumar DM                                                    #
#  Role  : Physical Design Engineer, ASIC Automation Engineer                  #
#                                                                              #
#  Copyright (c) 2026 LogicLance. All rights reserved.                         #
#                                                                              #
################################################################################

"""
Converts a Python config dictionary into a Vivado-compatible Tcl config file.
The generated file contains only 'set' statements that the Tcl flow scripts source.
"""

import os
from datetime import datetime


def _tcl_escape(value):
    """Escape a string for safe embedding in Tcl double-quotes."""
    s = str(value)
    s = s.replace("\\", "\\\\")
    s = s.replace('"', '\\"')
    s = s.replace("[", "\\[")
    s = s.replace("]", "\\]")
    s = s.replace("$", "\\$")
    return s


def _to_tcl_value(value):
    """Convert a Python value to a Tcl value string."""
    if isinstance(value, bool):
        return "1" if value else "0"
    elif isinstance(value, int):
        return str(value)
    elif isinstance(value, list):
        if not value:
            return "[list]"
        items = []
        for item in value:
            if isinstance(item, dict):
                # Test case dict: {name: "tc1", stdin: "/path", stdout: "/path"}
                pairs = []
                for k, v in item.items():
                    pairs.append(f'{k} "{_tcl_escape(v)}"')
                items.append("{" + " ".join(pairs) + "}")
            else:
                items.append(f'"{_tcl_escape(item)}"')
        return "[list \\\n  " + " \\\n  ".join(items) + " \\\n]"
    elif isinstance(value, str):
        return f'"{_tcl_escape(value)}"'
    else:
        return f'"{_tcl_escape(str(value))}"'


def generate_vivado_config_tcl(config, output_path, tool_dir=None):
    """
    Generate a _vivado_config.tcl file from a Python config dictionary.

    Args:
        config: dict with keys like 'project_xpr', 'tb_top', etc.
        output_path: path to write the .tcl file
        tool_dir: absolute path to the tool root (for TOOL_DIR variable)

    Returns:
        output_path on success
    """
    lines = []
    lines.append("# " + "=" * 64)
    lines.append("# Auto-generated by FPGA Automation Tool — DO NOT EDIT")
    lines.append(f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("# " + "=" * 64)
    lines.append("")

    # Set TOOL_DIR so Tcl scripts can find lib/utils.tcl
    if tool_dir:
        lines.append(f'set TOOL_DIR "{_tcl_escape(tool_dir)}"')
    else:
        lines.append('set TOOL_DIR [file dirname [file normalize [info script]]]')
    lines.append("")

    # Map Python config keys to Tcl variable names (uppercase)
    key_map = {
        # Project
        "project_xpr":      "PROJECT_XPR",
        "fpga_part":        "FPGA_PART",
        "board_part":       "BOARD_PART",
        "project_name":     "PROJECT_NAME",
        "project_dir":      "PROJECT_DIR",
        "ip_repo_paths":    "IP_REPO_PATHS",
        "source_files":     "SOURCE_FILES",
        "bd_tcl_script":    "BD_TCL_SCRIPT",
        # Testbench
        "tb_top":           "TB_TOP",
        "tb_files":         "TB_FILES",
        "tb_dir":           "TB_DIR",
        "tb_includes":      "TB_INCLUDES",
        "tb_defines":       "TB_DEFINES",
        # Simulation
        "sim_mode":         "SIM_MODE",
        "sim_type":         "SIM_TYPE",
        # C-Model
        "cmodel_enable":    "CMODEL_ENABLE",
        "cmodel_dir":       "CMODEL_DIR",
        "cmodel_clean_target": "CMODEL_CLEAN_TARGET",
        "cmodel_build_targets": "CMODEL_BUILD_TARGETS",
        "cmodel_run_target": "CMODEL_RUN_TARGET",
        "cmodel_stdin":     "CMODEL_STDIN",
        "cmodel_stdout":    "CMODEL_STDOUT",
        "cmodel_log":       "CMODEL_LOG",
        "cmodel_timeout":   "CMODEL_TIMEOUT",
        # Regression
        "test_cases":       "TEST_CASES",
        "result_file":      "RESULT_FILE",
        "pass_pattern":     "PASS_PATTERN",
        "fail_pattern":     "FAIL_PATTERN",
        "cmodel_out_fixed": "CMODEL_OUT_FIXED",
        "cmodel_log_dir":   "CMODEL_LOG_DIR",
        "sim_log_dir":      "SIM_LOG_DIR",
        # Git
        "git_enable":       "GIT_ENABLE",
        "git_repo":         "GIT_REPO",
        "git_commit":       "GIT_COMMIT",
        "git_dest":         "GIT_DEST",
        "git_subdir":       "GIT_SUBDIR",
        # Output
        "output_bit":       "OUTPUT_BIT",
        "output_xsa":       "OUTPUT_XSA",
        "synth_jobs":       "SYNTH_JOBS",
        "impl_jobs":        "IMPL_JOBS",
        "output_log_dir":   "OUTPUT_LOG_DIR",
        # Phase 3 strategy injection for optimizer
        "synth_strategy":   "SYNTH_STRATEGY",
        "impl_strategy":    "IMPL_STRATEGY",
        "synth_directive":  "SYNTH_DIRECTIVE",
        "impl_directive":   "IMPL_DIRECTIVE",
        # Phase 3: auto XDC creation when missing
        "auto_xdc_file":    "AUTO_XDC_FILE",
        "force_full_impl":  "FORCE_FULL_IMPL",
    }

    # Group outputs by section
    sections = {
        "PROJECT":    ["project_xpr", "fpga_part", "board_part", "project_name",
                       "project_dir", "ip_repo_paths", "source_files", "bd_tcl_script"],
        "TESTBENCH":  ["tb_top", "tb_files", "tb_dir", "tb_includes", "tb_defines"],
        "SIMULATION": ["sim_mode", "sim_type"],
        "C-MODEL":    ["cmodel_enable", "cmodel_dir", "cmodel_clean_target",
                       "cmodel_build_targets", "cmodel_run_target", "cmodel_stdin",
                       "cmodel_stdout", "cmodel_log", "cmodel_timeout"],
        "REGRESSION": ["test_cases", "result_file", "pass_pattern", "fail_pattern",
                       "cmodel_out_fixed", "cmodel_log_dir", "sim_log_dir"],
        "GIT":        ["git_enable", "git_repo", "git_commit", "git_dest", "git_subdir"],
        "OUTPUT":     ["output_bit", "output_xsa", "synth_jobs", "impl_jobs", "output_log_dir"],
        # Phase 3
        "STRATEGY":   ["synth_strategy", "impl_strategy", "synth_directive", "impl_directive"],
        "CONSTRAINTS": ["auto_xdc_file"],
        "FORCE": ["force_full_impl"],
    }

    for section_name, keys in sections.items():
        section_values = {k: config[k] for k in keys if k in config}
        if not section_values:
            continue
        lines.append(f"# ---- {section_name} ----")
        for py_key in keys:
            if py_key not in config:
                continue
            tcl_var = key_map.get(py_key, py_key.upper())
            tcl_val = _to_tcl_value(config[py_key])
            # Multi-line lists get their own formatting
            if "\n" in tcl_val:
                lines.append(f"set {tcl_var} {tcl_val}")
            else:
                lines.append(f'set {tcl_var} {tcl_val}')
        lines.append("")

    # Write file
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, 'w') as f:
        f.write("\n".join(lines) + "\n")

    return output_path
