# ================================================================
# Auto-generated by FPGA Automation Tool — DO NOT EDIT
# Generated: 2026-06-12 13:17:00
# ================================================================

set TOOL_DIR "/root/Desktop/LOG_FPGA/XSA_scripts1/tcl"

# ---- PROJECT ----
set PROJECT_XPR ""
set FPGA_PART "xc7z020clg400-1"
set BOARD_PART ""
set PROJECT_NAME "fpga_project"
set PROJECT_DIR "./fpga_project"
set IP_REPO_PATHS [list]
set SOURCE_FILES [list \
  "/root/Desktop/LOG_FPGA/XSA_scripts1/sample_testcase/rtl" \
]
set BD_TCL_SCRIPT ""

# ---- TESTBENCH ----
set TB_TOP "tb_adder"
set TB_FILES [list]
set TB_DIR "/root/Desktop/LOG_FPGA/XSA_scripts/sample_testcase/sim"
set TB_INCLUDES [list]
set TB_DEFINES [list \
  "SIM=1" \
]

# ---- SIMULATION ----
set SIM_MODE "post-implementation"
set SIM_TYPE "functional"

# ---- C-MODEL ----
set CMODEL_ENABLE 1
set CMODEL_DIR "/root/Desktop/LOG_FPGA/XSA_scripts/sample_testcase/c_model"
set CMODEL_CLEAN_TARGET "clean"
set CMODEL_BUILD_TARGETS [list]
set CMODEL_RUN_TARGET "manual"
set CMODEL_STDIN ""
set CMODEL_STDOUT ""
set CMODEL_LOG "./output/cmodel_run.log"
set CMODEL_TIMEOUT 900

# ---- REGRESSION ----
set TEST_CASES [list \
  {name "TC1" stdin "sample_testcase/test_cases/tc1_input.txt" stdout "/tmp/tc1_out.txt"} \
  {name "TC2" stdin "sample_testcase/test_cases/tc2_input.txt" stdout "/tmp/tc2_out.txt"} \
]
set RESULT_FILE "RESULT.txt"
set PASS_PATTERN "TEST_PASSED"
set FAIL_PATTERN "TEST_FAILED"
set CMODEL_OUT_FIXED "/tmp/fpga_cmodel_golden.txt"
set CMODEL_LOG_DIR "./output/cmodel_logs"
set SIM_LOG_DIR "./output/sim_logs"

# ---- GIT ----
set GIT_ENABLE 0
set GIT_REPO ""
set GIT_COMMIT ""
set GIT_DEST ""
set GIT_SUBDIR ""

# ---- OUTPUT ----
set OUTPUT_BIT ""
set OUTPUT_XSA ""
set SYNTH_JOBS 4
set IMPL_JOBS 8
set OUTPUT_LOG_DIR "/root/Desktop/LOG_FPGA/XSA_scripts1/output/fpga_20260612_131700"

